networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.25.0.0/16"
          gateway: "172.25.0.1"

services:
  neo4j:
    image: neo4j:latest
    container_name: 'devneo4j'
    volumes:
      - './neo4j/data:/data'
      - './neo4j/conf/:/conf'
      - './neo4j/logs:/logs'
      - './neo4j/plugins:/plugins'
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4JLABS_PLUGINS=["apoc","graph-data-science"]
      - NEO4J_AUTH=neo4j/AGH_2025
    restart: on-failure
    networks:
      net:
        ipv4_address: 172.25.0.2
    command: neo4j
    tty: true
  streamlit:
    build:
      dockerfile: dockerfile
    container_name: app
    volumes:
      - ./app:/app
    networks:
      net:
        ipv4_address: 172.25.0.3
    ports:
      - 8501:8501
    restart: on-failure
    tty: true